steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/node-backend", "./backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/node-backend"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "node-api",
        "--image",
        "gcr.io/$PROJECT_ID/node-backend",
        "--region",
        "asia-south1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
