name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./backend/  # Ensure this points to the correct directory

    strategy:
      matrix:
        node-version: [20.x]  # Using Node.js version 20.x

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'  # Point to the correct lock file

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build --if-present

    - name: 'Create .env file'
      run: |
       echo "MONGO_URL=mongodb+srv://utsav:utsav22082003@cluster0.gegt41i.mongodb.net/?retryWrites=true&w=majority" > .env
       echo "PORT=5000" >> .env
       echo "JWT_SECRET=at_nodejs_practical" >> .env

    - name: Restart application with PM2
      run: |
        pm2 stop at-nodejs-practical || true  # Stop the process if it's running
        pm2 start dist/index.js --name at-nodejs-practical  # Start or restart the process
        pm2 save  # Save the PM2 process list
      shell: bash

    - name: Check PM2 logs
      run: pm2 logs at-nodejs-practical --lines 50
      shell: bash

      # NOTE: Avoid echoing sensitive information in logs. Comment this step out in production.
