name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./backend/  # Ensure this points to the correct directory

    strategy:
      matrix:
        node-version: [20.x]  # Using Node.js version 20.x

    steps:
    - uses: actions/checkout@v4

    - name: List files in backend
      run: ls -al  # List files to ensure correct structure

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'  # Point to the correct lock file

    - name: Create .env file from GitHub secret
      run: echo "${{ secrets.PROD_ENV_FILE }}" > .env
      shell: bash

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build --if-present

    - name: Show secret value for debugging
      run: echo "${{ secrets.PROD_ENV_FILE }}"
      shell: bash

    - name: Check .env file contents
      run: cat .env
      shell: bash
      # NOTE: Avoid echoing sensitive information in logs. Comment this step out in production.
