name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./backend/

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v4

    - name: List files in backend
      run: ls -al

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Create .env file from GitHub secret
      run: echo "${{ secrets.PROD_ENV_FILE }}" > .env
      shell: bash

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build --if-present
