name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./backend/  # Set the default working directory to backend

    strategy:
      matrix:
        node-version: [20.x]  # Use Node.js version 14.x

    steps:
    - uses: actions/checkout@v4

    - name: List files in backend
      run: ls -al  # No need for working-directory here as it’s set globally

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Create .env file from GitHub secret
      run: echo "${{ secrets.PROD_ENV_FILE }}" > .env
      shell: bash

    - name: Install dependencies
      run: npm ci  # It will run in ./backend/ by default due to the `defaults` setting

    - name: Build the project
      run: npm run build --if-present

    - name: Run tests
      run: npm test
